In [1]:
import numpy as np 

In [2]:
myarr=np.array([3,6,32,7])

In [3]:
myarr

array([ 3,  6, 32,  7])

In [4]:
myarr.dtype

dtype('int32')

**Array creation: Conversion from other python structures**

In [5]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [6]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [7]:
listarray.dtype

dtype('int32')

In [8]:
listarray.shape

(3, 3)

In [9]:
listarray.size

9

In [10]:
zeros=np.zeros((2,5))

In [11]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
rng=np.arange(15)

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
lspace=np.linspace(1,50,12)

In [15]:
lspace


array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

In [16]:
emp=np.empty((4,6))

In [17]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.33646845e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 7.56599128e-307,
        1.11260144e-306, 6.89812281e-307, 2.22522596e-306]])

In [18]:
emp_like=np.empty_like(lspace)

In [19]:
emp_like

array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

In [20]:
ide=np.identity(45)

In [21]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [22]:
ide.shape

(45, 45)

In [23]:
arr=np.arange(99)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr=arr.reshape(3,33)

In [26]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [27]:
arr=arr.ravel()

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.shape

(99,)

In [30]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [31]:
ar = np.array(x)

In [32]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [33]:
ar.sum(axis=0)

array([12,  8,  9])

In [34]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [35]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [36]:
ar.flat

In [37]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [38]:
ar.ndim

2

In [39]:
ar.size

9

In [40]:
ar.nbytes

36

In [41]:
one=np.array([1,3,4,634,2])

In [42]:
one.argmax()

3

In [43]:
one.argmin()

0

In [44]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [46]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [47]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [48]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [50]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [51]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [52]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [53]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [54]:
ar.sum()

29

In [55]:
ar.min()

0

In [56]:
ar.max()

7

In [57]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [58]:
np.count_nonzero(ar)

8

In [59]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [60]:
import sys

In [61]:
py_ar=[0,4,55,2]

In [62]:
np_ar=np.array(py_ar)

In [63]:
np_ar

array([ 0,  4, 55,  2])

In [64]:
sys.getsizeof(1)*len(py_ar)

112

In [65]:
np_ar.itemsize*np_ar.size

16

In [66]:
np_ar.tolist()

[0, 4, 55, 2]